package model;

public enum Countries {
ALASKA,NW_TERRITORY,GREENLAND,ALBERTA,ONTARIO,QUEBEC,WESTERN_US,EASTERN_US,CETN_AMERICA,VENENZUELA,PERU,BRAZIL,ARGENTINA,ICELAND,SCANDINAVIA,
UKRAINE,GREAT_BRITAIN, N_EUROPE,W_EUROPE,S_EUROPE,N_AFRICA,EGYPT,E_AFRICA,CONGO,S_AFRICA,MADAGASCAR,SIBERIA,YAKUTSIK,KAMCHATKA,URAL,IRKUTSK,
AFGHANISTAN,MOGOLIA,JAPAN,CHINA,MIDDLE_EAST,INDIA,SIAM,INDOESIA,NEW_GUINEA,W_AUSTRALIA,E_AUSTRALIA
}
