package model;

public enum Countries {
ALASKA,NW_TERRITORY,GREENLAND,ALBERTA,
ONTARIO,QUEBEC,WESTERN_US,EASTERN_US,
CENT_AMERICA,VENENZUELA,PERU,BRAZIL,
ARGENTINA,ICELAND,SCANDINAVIA,
UKRAINE,GREAT_BRITAIN, N_EUROPE,
W_EUROPE,S_EUROPE,N_AFRICA,EGYPT,
E_AFRICA,CONGO,S_AFRICA,MADAGASCAR,
SIBERIA,YAKUTSK,KAMCHATKA,URAL,IRKUTSK,
AFGHANISTAN,MONGOLIA,JAPAN,CHINA,MIDDLE_EAST,
INDIA,SIAM,INDONESIA,NEW_GUINEA,W_AUSTRALIA,E_AUSTRALIA
}
